all:
	ndk-build
push:
	adb push libs/arm64-v8a/42 /data/42
clean:
	rm -rf bin
	rm -rf gen
	rm -rf libs
	rm -rf obj
	rm -rf build.xml
	rm -rf local.properties
	rm -rf proguard-project.txt
	rm -rf project.properties
