clean:
	rm -f */*.o */*.a
	rm -f */*.exe */*.out
	rm -f */*.dll */*.dylib */*.so
	make -s -C logcat+arm64+linux+cli clean
	make -s -C logcat+arm64+linux+tui clean
	make -s -C apk clean
	make -s -C ipa clean
	make -s -C uwp clean
