clean:
	rm -f */*.o */*.a */*.so
	make -s -C android clean
	make -s -C apk clean
	make -s -C ipa clean
	make -s -C uwp clean
	make -s -C driver.usb@x64.linux clean
	make -s -C driver.usb@x64.mac clean
	make -s -C driver.usb@x64.win clean
