howto:
	cat readme
clean:
	rm -f */*.o */*.a
	rm -f */*.exe */*.out
	make -s -C none+all+android+cli clean
	make -s -C none+all+android+tui clean
	make -s -C none+all+android+bitmap clean
	make -s -C none+all+android+anative clean
