clean:
	rm -f */*.o */*.a
	rm -f */*.exe */*.out
	rm -f */*.dll */*.dylib */*.so
	make -s -C none+arm64+android+cli clean
	make -s -C none+arm64+android+tui clean
	make -s -C apk clean
	make -s -C ipa clean
	make -s -C uwp clean
