LOCAL_PATH:=$(call my-dir)/../../..
include $(CLEAR_VARS)




#libboot0
LOCAL_SRC_FILES += \
library/libboot0/app/ndk/entry.c \
library/libboot0/app/ndk/serial.c \
library/libboot0/app/ndk/thread.c \
library/libboot0/app/memory.c \
library/libboot0/origin.c

#libboot1
LOCAL_SRC_FILES += \
library/libboot1/init/init.c \
library/libboot1/init/args.myml.c \
library/libboot1/init/args.mython.c \
library/libboot1/prep/prep.term.c \
library/libboot1/prep/prep.default.c \
library/libboot1/prep/prep.myml.c \
library/libboot1/prep/prep.mython.c \
library/libboot1/loop/loop.exiter.c \
library/libboot1/loop/loop.poller.c \
library/libboot1/loop/loop.pulser.c \
library/libboot1/loop/loop.realer.c \
library/libboot1/loop/loop.waiter.c \
library/libboot1/std/stdin.c \
library/libboot1/std/stdout.c \
library/libboot1/std/stdev.c \
library/libboot1/std/stdrel.c \
library/libboot1/worker.c


#libhard0
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES += \
library/libhard0/bare/cpu/x86/x86.fp.c \
library/libhard0/bare/cpu/x86/x86.port.c
endif
ifeq ($(TARGET_ARCH),x86_64)
LOCAL_SRC_FILES += \
library/libhard0/bare/cpu/x64/x64.fp.c \
library/libhard0/bare/cpu/x64/x64.port.c
endif
ifeq ($(TARGET_ARCH),arm)
LOCAL_SRC_FILES += \
library/libhard0/bare/cpu/arm/arm.fp.c
endif
ifeq ($(TARGET_ARCH),arm64)
LOCAL_SRC_FILES += \
library/libhard0/bare/cpu/arm64/arm64.fp.c
endif
ifeq ($(TARGET_ARCH),mips)
LOCAL_SRC_FILES += \
library/libhard0/bare/cpu/mips/mips.fp.c
endif
ifeq ($(TARGET_ARCH),mips64)
LOCAL_SRC_FILES += \
library/libhard0/bare/cpu/mips64/mips64.fp.c
endif
LOCAL_SRC_FILES += \
library/libhard0/linux/linux.wire.bt.c \
library/libhard0/linux/linux.wire.i2c.c \
library/libhard0/linux/linux.wire.gpio.c \
library/libhard0/linux/linux.wire.pci.c \
library/libhard0/linux/linux.wire.spi.c \
library/libhard0/linux/linux.wire.usb.c \
library/libhard0/linux/linux.wire.wifi.c \
library/libhard0/device.c

#libhard1
LOCAL_SRC_FILES += \
library/libhard1/sensor/sensor.icm20789.c \
library/libhard1/sensor/sensor.l3gd20.c \
library/libhard1/sensor/sensor.lsm9ds1.c \
library/libhard1/sensor/sensor.mpu9250.c \
library/libhard1/sensor/sensor.ms5611.c \
library/libhard1/hwinfo/hwinfo.acpi.c \
library/libhard1/hwinfo/hwinfo.dts.c \
library/libhard1/driver.c

#libsoft0
LOCAL_SRC_FILES += \
library/libsoft0/linux/linux.flow.epoll.c \
library/libsoft0/linux/linux.flow.socket.c \
library/libsoft0/linux/linux.flow.ptmx.c \
library/libsoft0/linux/linux.flow.tty.c \
library/libsoft0/linux/linux.memory.file.c \
library/libsoft0/linux/linux.memory.folder.c \
library/libsoft0/linux/linux.system.process.c \
library/libsoft0/linux/linux.system.random.c \
library/libsoft0/linux/linux.system.signal.c \
library/libsoft0/linux/linux.system.time.c \
library/libsoft0/system.c

#libsoft1
LOCAL_SRC_FILES += \
library/libsoft1/libalgo/liblang/assembly/asm.x64.c \
library/libsoft1/libalgo/liblang/assembly/asm.arm.c \
library/libsoft1/libalgo/liblang/program/prog.purec.c \
library/libsoft1/libalgo/liblang/program/prog.cpp.c \
library/libsoft1/libalgo/liblang/lang.c \
library/libsoft1/libalgo/libstr/conv/conv.arg.c \
library/libsoft1/libalgo/libstr/conv/conv.ascii.c \
library/libsoft1/libalgo/libstr/conv/conv.bigint.c \
library/libsoft1/libalgo/libstr/conv/conv.file.c \
library/libsoft1/libalgo/libstr/conv/conv.num.c \
library/libsoft1/libalgo/libstr/conv/conv.print.c \
library/libsoft1/libalgo/libstr/conv/conv.url.c \
library/libsoft1/libalgo/libstr/conv/conv.utf8.c \
library/libsoft1/libalgo/libstr/count/count.item.c \
library/libsoft1/libalgo/libstr/count/count.line.c \
library/libsoft1/libalgo/libstr/diff/diff.cmp.c \
library/libsoft1/libalgo/libstr/diff/diff.wild.c \
library/libsoft1/libalgo/libstr/move/move.copy.c \
library/libsoft1/libalgo/libstr/move/move.swap.c \
library/libsoft1/libalgo/crypt/crypt.aes.c \
library/libsoft1/libalgo/crypt/crypt.des.c \
library/libsoft1/libalgo/crypt/crypt.rsa.c \
library/libsoft1/libalgo/encdec/encdec.base64.c \
library/libsoft1/libalgo/encdec/encdec.qrcode.c \
library/libsoft1/libalgo/graph/graph.forcedirected.c \
library/libsoft1/libalgo/graph/graph.kruskal.c \
library/libsoft1/libalgo/graph/graph.prim.c \
library/libsoft1/libalgo/hash/hash.crc8.c \
library/libsoft1/libalgo/hash/hash.crc16.c \
library/libsoft1/libalgo/hash/hash.crc32.c \
library/libsoft1/libalgo/hash/hash.md5.c \
library/libsoft1/libalgo/hash/hash.sha1.c \
library/libsoft1/libalgo/hash/hash.sha256.c \
library/libsoft1/libalgo/hash/hash.sha512.c \
library/libsoft1/libalgo/hash/hash.string.c \
library/libsoft1/libalgo/keyexch/keyexch.dh.c \
library/libsoft1/libalgo/keyexch/keyexch.x25519.c \
library/libsoft1/libalgo/linear/linear.disjoint.c \
library/libsoft1/libalgo/linear/linear.memory.c \
library/libsoft1/libalgo/linear/linear.queue.c \
library/libsoft1/libalgo/linear/linear.stack.c \
library/libsoft1/libalgo/matching/match.bm.c \
library/libsoft1/libalgo/matching/match.kmp.c \
library/libsoft1/libalgo/matching/match.rough.c \
library/libsoft1/libalgo/neural/neural.ann.c \
library/libsoft1/libalgo/neural/neural.cnn.c \
library/libsoft1/libalgo/neural/neural.rnn.c \
library/libsoft1/libalgo/notation/nota.calc.c \
library/libsoft1/libalgo/notation/nota.postfix.c \
library/libsoft1/libalgo/notation/nota.prefix.c \
library/libsoft1/libalgo/solve/solve.2048.c \
library/libsoft1/libalgo/solve/solve.chess.c \
library/libsoft1/libalgo/solve/solve.maze.c \
library/libsoft1/libalgo/solve/solve.pcbwire.c \
library/libsoft1/libalgo/solve/solve.rubik.c \
library/libsoft1/libalgo/solve/solve.snake.c \
library/libsoft1/libalgo/solve/solve.sudoku.c \
library/libsoft1/libalgo/solve/solve.tetris.c \
library/libsoft1/libalgo/solve/solve.xiangqi.c \
library/libsoft1/libalgo/sorting/sort.bubble.c \
library/libsoft1/libalgo/sorting/sort.gnome.c \
library/libsoft1/libalgo/sorting/sort.heap.c \
library/libsoft1/libalgo/sorting/sort.insert.c \
library/libsoft1/libalgo/sorting/sort.merge.c \
library/libsoft1/libalgo/sorting/sort.quick.c \
library/libsoft1/libalgo/sorting/sort.select.c \
library/libsoft1/libalgo/transform/trfm.cosine.c \
library/libsoft1/libalgo/transform/trfm.fourier.c \
library/libsoft1/libalgo/transform/trfm.laplace.c \
library/libsoft1/libalgo/tree/tree.binary.c \
library/libsoft1/libalgo/tree/tree.redblack.c \
library/libsoft1/libalgo/tree/tree.bplus.c \
library/libsoft1/libchem/chem.equation.c \
library/libsoft1/libfile/audio/audio.ape.c \
library/libsoft1/libfile/audio/audio.mp3.c \
library/libsoft1/libfile/audio/audio.ogg.c \
library/libsoft1/libfile/audio/audio.wav.c \
library/libsoft1/libfile/audio/tone.drum.c \
library/libsoft1/libfile/audio/tone.flute.c \
library/libsoft1/libfile/audio/tone.piano.c \
library/libsoft1/libfile/audio/tone.violin.c \
library/libsoft1/libfile/certificate/cert.pem.c \
library/libsoft1/libfile/certificate/cert.x509.c \
library/libsoft1/libfile/compress/comp.7z.c \
library/libsoft1/libfile/compress/comp.cpio.c \
library/libsoft1/libfile/compress/comp.gz.c \
library/libsoft1/libfile/compress/comp.tar.c \
library/libsoft1/libfile/compress/comp.zip.c \
library/libsoft1/libfile/document/doc.doc.c \
library/libsoft1/libfile/document/doc.docx.c \
library/libsoft1/libfile/document/doc.latex.c \
library/libsoft1/libfile/document/doc.pdf.c \
library/libsoft1/libfile/document/doc.ppt.c \
library/libsoft1/libfile/document/doc.pptx.c \
library/libsoft1/libfile/document/doc.xls.c \
library/libsoft1/libfile/document/doc.xlsx.c \
library/libsoft1/libfile/electronic/ee.brd.c \
library/libsoft1/libfile/electronic/ee.dsn.c \
library/libsoft1/libfile/electronic/ee.pcbdoc.c \
library/libsoft1/libfile/electronic/ee.schdoc.c \
library/libsoft1/libfile/executable/exec.elf.c \
library/libsoft1/libfile/executable/exec.macho.c \
library/libsoft1/libfile/executable/exec.pe.c \
library/libsoft1/libfile/filesystem/fs.ext.c \
library/libsoft1/libfile/filesystem/fs.fat.c \
library/libsoft1/libfile/filesystem/fs.hfs.c \
library/libsoft1/libfile/filesystem/fs.ntfs.c \
library/libsoft1/libfile/font/font.fon.c \
library/libsoft1/libfile/font/font.otf.c \
library/libsoft1/libfile/font/font.ttf.c \
library/libsoft1/libfile/model/model.3mf.c \
library/libsoft1/libfile/model/model.dwg.c \
library/libsoft1/libfile/model/model.stl.c \
library/libsoft1/libfile/parttable/pt.apple.c \
library/libsoft1/libfile/parttable/pt.gpt.c \
library/libsoft1/libfile/parttable/pt.mbr.c \
library/libsoft1/libfile/picture/pic.bmp.c \
library/libsoft1/libfile/picture/pic.flif.c \
library/libsoft1/libfile/picture/pic.heif.c \
library/libsoft1/libfile/picture/pic.jpg.c \
library/libsoft1/libfile/picture/pic.png.c \
library/libsoft1/libfile/picture/pic.webp.c \
library/libsoft1/libfile/vdisk/disk.raw.c \
library/libsoft1/libfile/vdisk/disk.vhd.c \
library/libsoft1/libfile/vdisk/disk.vmdk.c \
library/libsoft1/libfile/video/video.avi.c \
library/libsoft1/libfile/video/video.gif.c \
library/libsoft1/libfile/video/video.mkv.c \
library/libsoft1/libfile/video/video.mp4.c \
library/libsoft1/libfile/video/video.rmvb.c \
library/libsoft1/libfile/file.c \
library/libsoft1/libmath/libmath.bigint.c \
library/libsoft1/libmath/libmath.matrix.c \
library/libsoft1/libmath/libmath.notation.c \
library/libsoft1/libmath/libmath.prime.c \
library/libsoft1/libmath/libmath.quaternion.c \
library/libsoft1/libmath/libmath.vector.c \
library/libsoft1/libflow/0.phy/phy.bt.c \
library/libsoft1/libflow/0.phy/phy.eth.c \
library/libsoft1/libflow/0.phy/phy.raw.c \
library/libsoft1/libflow/0.phy/phy.wlan.c \
library/libsoft1/libflow/1.link/link.arp.c \
library/libsoft1/libflow/1.link/link.ipv4.c \
library/libsoft1/libflow/1.link/link.ipv6.c \
library/libsoft1/libflow/1.link/link.ipx.c \
library/libsoft1/libflow/1.link/link.pppoe.c \
library/libsoft1/libflow/1.link/link.slip.c \
library/libsoft1/libflow/2.ip/ip46.icmp.c \
library/libsoft1/libflow/2.ip/ip46.tcp.c \
library/libsoft1/libflow/2.ip/ip46.udp.c \
library/libsoft1/libflow/2.ip/ipx.spx.c \
library/libsoft1/libflow/3.udp/udp.bootp.c \
library/libsoft1/libflow/3.udp/udp.dhcp.c \
library/libsoft1/libflow/3.udp/udp.dns.c \
library/libsoft1/libflow/3.udp/udp.ntp.c \
library/libsoft1/libflow/3.udp/udp.trav.c \
library/libsoft1/libflow/3.udp/udp.quic.c \
library/libsoft1/libflow/3.udp/udp.tftp.c \
library/libsoft1/libflow/4.tcp/tcp.dl.c \
library/libsoft1/libflow/4.tcp/tcp.ftp.c \
library/libsoft1/libflow/4.tcp/tcp.fuckgfw.c \
library/libsoft1/libflow/4.tcp/tcp.http.c \
library/libsoft1/libflow/4.tcp/tcp.party.c \
library/libsoft1/libflow/4.tcp/tcp.proxy.c \
library/libsoft1/libflow/4.tcp/tcp.rdp.c \
library/libsoft1/libflow/4.tcp/tcp.rtmp.c \
library/libsoft1/libflow/4.tcp/tcp.sql.c \
library/libsoft1/libflow/4.tcp/tcp.socks.c \
library/libsoft1/libflow/4.tcp/tcp.trav.c \
library/libsoft1/libflow/4.tcp/tcp.vnc.c \
library/libsoft1/libflow/4.tcp/tcp.ssh.c \
library/libsoft1/libflow/4.tcp/tcp.telnet.c \
library/libsoft1/libflow/4.tcp/tcp.tls1_2.c \
library/libsoft1/libflow/4.tcp/tcp.tls1_3.c \
library/libsoft1/libflow/4.tcp/tcp.ws.c \
library/libsoft1/libflow/ahrs/ahrs.ekf.c \
library/libsoft1/libflow/ahrs/ahrs.madgwick.c \
library/libsoft1/libflow/ahrs/ahrs.mahony.c \
library/libsoft1/libflow/ahrs/ahrs.only_g.c \
library/libsoft1/libflow/ahrs/ahrs.only_ga.c \
library/libsoft1/libflow/ahrs/ahrs.ukf.c \
library/libsoft1/libflow/stream/stream.help.control.c \
library/libsoft1/libflow/stream/stream.help.search.c \
library/libsoft1/libflow/stream/stream.help.vt100.c \
library/libsoft1/libflow/stream/stream.conv.qu2eu.c \
library/libsoft1/libflow/stream/stream.conv.str2vec.c \
library/libsoft1/libflow/stream/stream.image.rotate.c \
library/libsoft1/libflow/stream/stream.image.scale.c \
library/libsoft1/libflow/stream/stream.mux.easy.c \
library/libsoft1/libflow/stream/stream.mux.media.c \
library/libsoft1/libflow/stream/stream.parse.gcode.c \
library/libsoft1/libflow/stream/stream.parse.mavlink.c \
library/libsoft1/libflow/stream/stream.parse.nema0183.c \
library/libsoft1/libflow/stream/stream.revise.recut.c \
library/libsoft1/libflow/stream/stream.revise.reline.c \
library/libsoft1/libflow/stream/stream.revise.reorder.c \
library/libsoft1/libflow/stream/stream.test.echo.c \
library/libsoft1/libflow/stream/stream.test.goslow.c \
library/libsoft1/libflow/stream/stream.test.pump.c \
library/libsoft1/libflow/stream/stream.test.stor.c \
library/libsoft1/libflow/stream/stream.test.dbgf32.c \
library/libsoft1/libflow/stream/stream.test.dbghex.c \
library/libsoft1/libflow/stream/stream.test.fftpcm.c \
library/libsoft1/libflow/stream/stream.test.fftrgb.c \
library/libsoft1/artery.c

#libuser0
LOCAL_SRC_FILES += \
library/libuser0/r2v-sensor/sensor.ahrs.c \
library/libuser0/r2v-sensor/sensor.slam.c \
library/libuser0/r2v-sensor/sensor.lidar.c \
library/libuser0/r2v-sensor/sensor.radar.c \
library/libuser0/v2r-gadget/1602/gadget.1602.c \
library/libuser0/v2r-gadget/12864/gadget.12864.c \
library/libuser0/v2r-window/lib-gl/gldraw/gl.coop.c \
library/libuser0/v2r-window/lib-gl/gldraw/gl.easy.c \
library/libuser0/v2r-window/lib-gl/gldraw/gl.full.c \
library/libuser0/v2r-window/lib-gl/gldraw/gl.none.c \
library/libuser0/v2r-window/lib-gl/globj/globj.fbo.c \
library/libuser0/v2r-window/lib-gl/globj/globj.shader.c \
library/libuser0/v2r-window/lib-gl/globj/globj.texture.c \
library/libuser0/v2r-window/lib-gl/globj/globj.varray.c \
library/libuser0/v2r-window/lib-gl/globj/globj.vertex.c \
library/libuser0/v2r-window/lib-gl/gltar/gl41.target.color.c \
library/libuser0/v2r-window/lib-gl/gltar/gl41.target.depth.c \
library/libuser0/v2r-window/lib-gl/gltar/gl41.target.gbuffer.c \
library/libuser0/v2r-window/lib-gl/gltar/gl41.target.window.c \
library/libuser0/v2r-window/os-android/android.gles.c \
library/libuser0/v2r-speaker/os-android/android.speaker.c \
library/libuser0/r2v-camera/os-android/android.cam.c \
library/libuser0/r2v-micphone/os-android/android.mic.c \
library/libuser0/w2w-cmdline/android/android.stdio.c \
library/libuser0/w2w-gamepad/android/android.gamepad.c \
library/libuser0/w2w-systray/android/android.tray.c \
library/libuser0/supply.c

#libuser1
LOCAL_SRC_FILES += \
library/libuser1/forfile/html/html.help.c \
library/libuser1/forfile/json/json.c \
library/libuser1/forfile/xml/xml.c \
library/libuser1/forfile/zimu/zimu.c \
library/libuser1/forgpu/gl10/gl10.ctx.c \
library/libuser1/forgpu/gl10/gl10.draw.c \
library/libuser1/forgpu/gl10/gl10.fbo.c \
library/libuser1/forgpu/gl41/carve/carve3d.opaque.point.c \
library/libuser1/forgpu/gl41/carve/carve3d.opaque.line.c \
library/libuser1/forgpu/gl41/carve/carve3d.opaque.trigon.c \
library/libuser1/forgpu/gl41/carve/carve3d.solid.point.c \
library/libuser1/forgpu/gl41/carve/carve3d.solid.line.c \
library/libuser1/forgpu/gl41/carve/carve3d.solid.trigon.c \
library/libuser1/forgpu/gl41/carve/carve3d.texed.ascii.c \
library/libuser1/forgpu/gl41/carve/carve3d.texed.craft.c \
library/libuser1/forgpu/gl41/carve/carve3d.other.circuit.c \
library/libuser1/forgpu/gl41/carve/carve3d.other.group.c \
library/libuser1/forgpu/gl41/carve/carve3d.other.helper.c \
library/libuser1/forgpu/gl41/gl41.coop.c \
library/libuser1/forgpu/gl41/gl41.data.c \
library/libuser1/forcpu/rgba/draw/draw.line.c \
library/libuser1/forcpu/rgba/draw/draw.solid.c \
library/libuser1/forcpu/rgba/draw/draw.shape.c \
library/libuser1/forcpu/rgba/draw/draw.ascii.c \
library/libuser1/forcpu/rgba/draw/draw.utf8.c \
library/libuser1/forcpu/rgba/draw/draw.vt100.c \
library/libuser1/forcpu/rgba/rgba.c \
library/libuser1/forcpu/yuv/yuv.c \
library/libuser1/forcpu/tui/tui.c \
library/libuser1/forcpu/cli/cli.c \
library/libuser1/forspu/al10/al10.c \
library/libuser1/forspu/sl10/sl10.c \
library/libuser1/forspu/spu.pcm.c \
library/libuser1/forpin/bionic/robot-arm.c \
library/libuser1/forpin/bionic/robot-dog.c \
library/libuser1/forpin/bionic/robot-man.c \
library/libuser1/forpin/bionic/robot-snake.c \
library/libuser1/forpin/copter/copter-hexa.c \
library/libuser1/forpin/copter/copter-octo.c \
library/libuser1/forpin/copter/copter-quad.c \
library/libuser1/forpin/factory/3d-printer.c \
library/libuser1/forpin/factory/3d-router.c \
library/libuser1/forpin/vehicle/car-bldc.c \
library/libuser1/forpin/vehicle/car-step.c \
library/libuser1/forpin/vehicle/car-toy.c \
library/libuser1/therule/aiding/1d/lib1d.c \
library/libuser1/therule/aiding/1d/json/json.c \
library/libuser1/therule/aiding/1d/latex/latex.c \
library/libuser1/therule/aiding/1d/xml/xaml.c \
library/libuser1/therule/aiding/1d/xml/xml.c \
library/libuser1/therule/aiding/2d/lib2d.c \
library/libuser1/therule/aiding/2d/photo/photo.blur.c \
library/libuser1/therule/aiding/2d/photo/photo.channel.c \
library/libuser1/therule/aiding/2d/photo/photo.convert.c \
library/libuser1/therule/aiding/2d/photo/photo.gray.c \
library/libuser1/therule/aiding/2d/photo/photo.mosaic.c \
library/libuser1/therule/aiding/2d/photo/photo.rotate.c \
library/libuser1/therule/aiding/2d/photo/photo.scale.c \
library/libuser1/therule/aiding/3d/lib3d.c \
library/libuser1/therule/aiding/3d/matrix/mat.local2world.c \
library/libuser1/therule/aiding/3d/matrix/mat.world2camera.c \
library/libuser1/therule/aiding/3d/matrix/mat.camera2ndc.c \
library/libuser1/therule/aiding/3d/matrix/mat.aid.c \
library/libuser1/therule/aiding/3d/intersect/intersect.obb.c \
library/libuser1/therule/aiding/3d/intersect/intersect.ray.c \
library/libuser1/therule/aiding/3d/intersect/intersect.rect.c \
library/libuser1/therule/aiding/3d/intersect/intersect.sphere.c \
library/libuser1/therule/aiding/4d/lib4d.c \
library/libuser1/therule/aiding/4d/asset.circuit.c \
library/libuser1/therule/aiding/4d/asset.function.c \
library/libuser1/therule/aiding/4d/asset.html.c \
library/libuser1/therule/aiding/4d/asset.image.c \
library/libuser1/therule/aiding/4d/asset.model.c \
library/libuser1/therule/aiding/4d/asset.sound.c \
library/libuser1/therule/event/evcam/evcam.1rd.c \
library/libuser1/therule/event/evcam/evcam.3rd.c \
library/libuser1/therule/event/evcam/evcam.free.c \
library/libuser1/therule/event/evcam/evcam.frus.c \
library/libuser1/therule/event/evcam/evcam.rts.c \
library/libuser1/therule/event/evpick/evpick.area.c \
library/libuser1/therule/event/evpick/evpick.ray.c \
library/libuser1/therule/event/evtouch/evtouch.movecam.c \
library/libuser1/therule/event/evtouch/evtouch.moveobj.c \
library/libuser1/therule/gameplay/interact/play.interact.c \
library/libuser1/therule/gameplay/mission/play.mission.c \
library/libuser1/therule/nature/collide/collide.simple.c \
library/libuser1/therule/nature/gravity/gravity.simple.c \
library/libuser1/therule/rule.c \
library/libuser1/themind/elec/bldc/control.bldc.c \
library/libuser1/themind/elec/bulk/control.bulk.c \
library/libuser1/themind/pilot/drone/pilot.drone.c \
library/libuser1/themind/pilot/vehicle/pilot.vehicle.c \
library/libuser1/themind/pilot/follow/pilot.follow.c \
library/libuser1/themind/pilot/lookat/pilot.lookat.c \
library/libuser1/themind/pilot/wander/pilot.wander.c \
library/libuser1/themind/place/maze/solve.maze.c \
library/libuser1/themind/place/rubik/solve.rubik.c \
library/libuser1/themind/user/baby/baby.c \
library/libuser1/themind/user/gary/gary.c \
library/libuser1/themind/user/john/john.c \
library/libuser1/themind/user/kali/kali.c \
library/libuser1/themind/user/kirk/kirk.c \
library/libuser1/themind/user/lara/lara.c \
library/libuser1/themind/user/lily/lily.c \
library/libuser1/themind/user/musk/musk.c \
library/libuser1/themind/user/rose/rose.c \
library/libuser1/themind/user/yoda/yoda.c \
library/libuser1/themind/mind.c \
library/libuser1/theworld/scene/biology/bio.evolution.c \
library/libuser1/theworld/scene/biology/bio.multiply.c \
library/libuser1/theworld/scene/biology/bio.plague.c \
library/libuser1/theworld/scene/chemic/chem.corrode.c \
library/libuser1/theworld/scene/electric/ee.analog.c \
library/libuser1/theworld/scene/electric/ee.digital.c \
library/libuser1/theworld/scene/factory/fac.gcode.c \
library/libuser1/theworld/scene/factory/fac.gerber.c \
library/libuser1/theworld/scene/physic/phy.field.c \
library/libuser1/theworld/scene/physic/phy.fluid.c \
library/libuser1/theworld/scene/physic/phy.force.c \
library/libuser1/theworld/scene/neural/nn.cnn.c \
library/libuser1/theworld/scene/neural/nn.rnn.c \
library/libuser1/theworld/scene/uiux/uiux.border.c \
library/libuser1/theworld/scene/uiux/uiux.frame.c \
library/libuser1/theworld/scene/uiux/uiux.guide.c \
library/libuser1/theworld/scene/scene.c \
library/libuser1/theworld/whole/3d.real.c \
library/libuser1/theworld/whole/3d.virt.c \
library/libuser1/theworld/whole/ui.html.c \
library/libuser1/theworld/whole/ui.xaml.c \
library/libuser1/theworld/whole/vm.mmio.c \
library/libuser1/theworld/whole/vm.port.c \
library/libuser1/theworld/world.c \
library/libuser1/thething/file/file.model.scad.c \
library/libuser1/thething/file/file.model.geometry.c \
library/libuser1/thething/file/file.common.hexedit.c \
library/libuser1/thething/file/file.text.editor.c \
library/libuser1/thething/file/file.program.mips64.c \
library/libuser1/thething/file/file.biology.fasta.c \
library/libuser1/thething/file/file.biology.dna.c \
library/libuser1/thething/file/file.model.stl.c \
library/libuser1/thething/file/file.program.arm64.c \
library/libuser1/thething/file/file.model.obj.c \
library/libuser1/thething/file/file.common.folder.c \
library/libuser1/thething/file/file.text.cpure.c \
library/libuser1/thething/file/file.text.java.c \
library/libuser1/thething/file/file.program.x86_64.c \
library/libuser1/thething/file/file.text.cplus.c \
library/libuser1/thething/game/2048/game.2048.c \
library/libuser1/thething/game/gobang/game.gobang.c \
library/libuser1/thething/game/poker/poker.c \
library/libuser1/thething/game/puzzle/game.puzzle.c \
library/libuser1/thething/game/tetris/game.tetris.c \
library/libuser1/thething/game/krieg/game.krieg.c \
library/libuser1/thething/game/weiqi/game.weiqi.c \
library/libuser1/thething/game/sudoku/game.sudoku.c \
library/libuser1/thething/game/maze/game.maze.c \
library/libuser1/thething/game/brick/game.brick.c \
library/libuser1/thething/game/mahjong/mahjong.c \
library/libuser1/thething/game/rubik/game.rubik.c \
library/libuser1/thething/game/chess/game.chess.c \
library/libuser1/thething/game/ooxx/game.ooxx.c \
library/libuser1/thething/game/pegged/game.pegged.c \
library/libuser1/thething/game/xiangqi/game.xiangqi.c \
library/libuser1/thething/game/snake/game.snake.c \
library/libuser1/thething/game/sokoban/game.sokoban.c \
library/libuser1/thething/game/klotski/game.klotski.c \
library/libuser1/thething/onlycam/dxgl/dxgl.texball.c \
library/libuser1/thething/onlycam/dxgl/dxgl.skydome.c \
library/libuser1/thething/onlycam/dxgl/dxgl.texbox.c \
library/libuser1/thething/onlycam/dxgl/dxgl.weather.c \
library/libuser1/thething/onlycam/dxgl/dxgl.ground.c \
library/libuser1/thething/onlycam/dxgl/dxgl.terrain.c \
library/libuser1/thething/onlycam/dxgl/dxgl.field.c \
library/libuser1/thething/onlycam/dxgl/dxgl.particle.c \
library/libuser1/thething/onlycam/cam/cam.free.c \
library/libuser1/thething/onlycam/cam/cam.ortho.c \
library/libuser1/thething/onlycam/cam/cam.vrglass.c \
library/libuser1/thething/onlycam/pull/fbo.cbuf.c \
library/libuser1/thething/onlycam/pull/fbo.gbuf.c \
library/libuser1/thething/onlycam/push/fbo.mirror.c \
library/libuser1/thething/onlycam/push/fbo.portal.c \
library/libuser1/thething/onlycam/push/fbo.water.c \
library/libuser1/thething/onlycam/push/fbo.glass.c \
library/libuser1/thething/onlycam/light/light.direction.c \
library/libuser1/thething/onlycam/light/light.imagebased.c \
library/libuser1/thething/onlycam/light/light.point.c \
library/libuser1/thething/onlycam/light/light.projector.c \
library/libuser1/thething/onlycam/light/light.spot.c \
library/libuser1/thething/onlymic/mic/mic.mono.c \
library/libuser1/thething/onlymic/mic/mic.stereo.c \
library/libuser1/thething/reallife/animal/animal.dog.c \
library/libuser1/thething/reallife/animal/animal.human.c \
library/libuser1/thething/reallife/animal/animal.spider.c \
library/libuser1/thething/reallife/funland/item.ferris.c \
library/libuser1/thething/reallife/funland/item.roller.c \
library/libuser1/thething/reallife/galaxy/item.planet.c \
library/libuser1/thething/reallife/galaxy/item.satellite.c \
library/libuser1/thething/reallife/gear/gear.hypoid.c \
library/libuser1/thething/reallife/gear/gear.worm.c \
library/libuser1/thething/reallife/gear/gear.helical.c \
library/libuser1/thething/reallife/gear/gear.spur.c \
library/libuser1/thething/reallife/gear/gear.bevel.c \
library/libuser1/thething/reallife/home/real.screen.c \
library/libuser1/thething/reallife/home/item.piano.c \
library/libuser1/thething/reallife/home/dxgl.curtain.c \
library/libuser1/thething/reallife/home/item.clock.c \
library/libuser1/thething/reallife/home/item.house.c \
library/libuser1/thething/reallife/home/real.speaker.c \
library/libuser1/thething/reallife/mechan/item.spring.c \
library/libuser1/thething/reallife/mechan/item.motor.c \
library/libuser1/thething/reallife/mechan/item.stick.c \
library/libuser1/thething/reallife/move/move.ladder.c \
library/libuser1/thething/reallife/move/move.stair.c \
library/libuser1/thething/reallife/move/move.elevator.c \
library/libuser1/thething/reallife/move/move.telpher.c \
library/libuser1/thething/reallife/organ/real.theeye.c \
library/libuser1/thething/reallife/organ/real.theear.c \
library/libuser1/thething/reallife/plant/item.tree.c \
library/libuser1/thething/reallife/plant/item.grass.c \
library/libuser1/thething/reallife/plant/item.flower.c \
library/libuser1/thething/reallife/reducer/redu.harmonic.c \
library/libuser1/thething/reallife/reducer/redu.cycloid.c \
library/libuser1/thething/reallife/reducer/redu.planetary.c \
library/libuser1/thething/reallife/robot/robo.dancemat.c \
library/libuser1/thething/reallife/robot/robo.otto.c \
library/libuser1/thething/reallife/robot/robo.balance.c \
library/libuser1/thething/reallife/robot/robo.rccar.c \
library/libuser1/thething/reallife/robot/robo.drone.c \
library/libuser1/thething/subject/elec/analog/dcdc/dcdc.bulk.c \
library/libuser1/thething/subject/elec/analog/dcdc/dcdc.boost.c \
library/libuser1/thething/subject/elec/analog/radio/radio.am.c \
library/libuser1/thething/subject/elec/analog/radio/radio.fm.c \
library/libuser1/thething/subject/elec/analog/acdc/acdc.rectifier.c \
library/libuser1/thething/subject/elec/analog/energy/energy.battery.c \
library/libuser1/thething/subject/elec/analog/energy/energy.current.c \
library/libuser1/thething/subject/elec/analog/energy/energy.voltage.c \
library/libuser1/thething/subject/elec/analog/dcac/acdc.hbridge.c \
library/libuser1/thething/subject/elec/analog/acac/acac.transform.c \
library/libuser1/thething/subject/elec/semi/transis/chip.transistor.mosfet.c \
library/libuser1/thething/subject/elec/semi/transis/chip.transistor.finfet.c \
library/libuser1/thething/subject/elec/semi/transis/chip.transistor.bjt.c \
library/libuser1/thething/subject/elec/semi/transis/chip.transistor.gaafet.c \
library/libuser1/thething/subject/elec/semi/diode/chip.diode.zener.c \
library/libuser1/thething/subject/elec/semi/diode/chip.diode.emitting.c \
library/libuser1/thething/subject/elec/semi/diode/chip.diode.schottky.c \
library/libuser1/thething/subject/elec/common/common.inductor.c \
library/libuser1/thething/subject/elec/common/common.memristor.c \
library/libuser1/thething/subject/elec/common/common.capacitor.c \
library/libuser1/thething/subject/elec/common/common.resistor.c \
library/libuser1/thething/subject/elec/cmos/stor-ff/chip.flipflop.tff.c \
library/libuser1/thething/subject/elec/cmos/stor-ff/chip.flipflop.jkff.c \
library/libuser1/thething/subject/elec/cmos/stor-ff/chip.flipflop.dff.c \
library/libuser1/thething/subject/elec/cmos/oper-add/chip.adder.half.c \
library/libuser1/thething/subject/elec/cmos/oper-add/chip.adder.full.c \
library/libuser1/thething/subject/elec/cmos/gate-trans/chip.tran.tristate.c \
library/libuser1/thething/subject/elec/cmos/gate-trans/chip.tran.tg.c \
library/libuser1/thething/subject/elec/cmos/gate-trans/chip.tran.mux.c \
library/libuser1/thething/subject/elec/cmos/stor-ram/chip.ram.static.c \
library/libuser1/thething/subject/elec/cmos/stor-ram/chip.ram.feedback.c \
library/libuser1/thething/subject/elec/cmos/stor-ram/chip.ram.dynamic.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.not.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.and.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.xor.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.nor.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.nand.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.or.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.xnor.c \
library/libuser1/thething/subject/elec/cmos/gate-logic/chip.logic.autocmos.c \
library/libuser1/thething/subject/elec/cmos/chip.fet.pmos.c \
library/libuser1/thething/subject/elec/cmos/chip.fet.nmos.c \
library/libuser1/thething/subject/topo/item.klein.c \
library/libuser1/thething/subject/topo/item.mobius.c \
library/libuser1/thething/subject/algo/algo.bintree.c \
library/libuser1/thething/subject/algo/algo.algo.c \
library/libuser1/thething/subject/algo/algo.mnist.c \
library/libuser1/thething/subject/algo/algo.link.c \
library/libuser1/thething/subject/algo/algo.sort.c \
library/libuser1/thething/subject/algo/algo.graph.c \
library/libuser1/thething/subject/algo/algo.bplus.c \
library/libuser1/thething/subject/code/code.call.c \
library/libuser1/thething/subject/code/code.for.c \
library/libuser1/thething/subject/code/code.if.c \
library/libuser1/thething/subject/code/code.jump.c \
library/libuser1/thething/subject/html/html.audio.c \
library/libuser1/thething/subject/html/html.p.c \
library/libuser1/thething/subject/html/html.button.c \
library/libuser1/thething/subject/html/html.ul.c \
library/libuser1/thething/subject/html/html.img.c \
library/libuser1/thething/subject/html/html.a.c \
library/libuser1/thething/subject/html/html.canvas.c \
library/libuser1/thething/subject/html/html.div.c \
library/libuser1/thething/subject/html/html.script.c \
library/libuser1/thething/subject/html/html.video.c \
library/libuser1/thething/subject/math/math.muldiv.c \
library/libuser1/thething/subject/math/math.exponent.c \
library/libuser1/thething/subject/math/math.vector.c \
library/libuser1/thething/subject/math/math.integral.c \
library/libuser1/thething/subject/math/math.matrix.c \
library/libuser1/thething/subject/math/math.differential.c \
library/libuser1/thething/subject/math/math.sincos.c \
library/libuser1/thething/subject/math/math.addsub.c \
library/libuser1/thething/subject/phys/phys.hydrogen.c \
library/libuser1/thething/subject/phys/phys.carbon.c \
library/libuser1/thething/subject/phys/phys.oxygen.c \
library/libuser1/thething/subject/chem/chem.graphene.c \
library/libuser1/thething/subject/chem/chem.h2o.c \
library/libuser1/thething/subject/chem/chem.ch4.c \
library/libuser1/thething/subject/chem/chem.diamond.c \
library/libuser1/thething/uiuxitem/bar/bar.skill.c \
library/libuser1/thething/uiuxitem/bar/bar.health.c \
library/libuser1/thething/uiuxitem/bar/bar.tag.c \
library/libuser1/thething/uiuxitem/bar/bar.tab.c \
library/libuser1/thething/uiuxitem/bar/bar.nav.c \
library/libuser1/thething/uiuxitem/bar/bar.list.c \
library/libuser1/thething/uiuxitem/debug/uiux.layouter.c \
library/libuser1/thething/uiuxitem/debug/uiux.corner.c \
library/libuser1/thething/uiuxitem/debug/uiux.cameraer.c \
library/libuser1/thething/uiuxitem/debug/uiux.pointer.c \
library/libuser1/thething/uiuxitem/menu/menu.login.c \
library/libuser1/thething/uiuxitem/menu/menu.confirm.c \
library/libuser1/thething/uiuxitem/menu/menu.esc.c \
library/libuser1/thething/uiuxitem/menu/menu.start.c \
library/libuser1/thething/uiuxitem/rtsui/rtsui.minimap.c \
library/libuser1/thething/uiuxitem/rtsui/rtsui.status.c \
library/libuser1/thething/uiuxitem/rtsui/rtsui.skill.c \
library/libuser1/thething/uiuxitem/table/tab.karnaugh.c \
library/libuser1/thething/uiuxitem/table/tab.truth.c \
library/libuser1/thething/uiuxitem/widget/uiux.picture.c \
library/libuser1/thething/uiuxitem/widget/vkbd.button.c \
library/libuser1/thething/uiuxitem/widget/uiux.qrcode.c \
library/libuser1/thething/uiuxitem/widget/vkbd.slider.c \
library/libuser1/thething/uiuxitem/widget/vkbd.joystick.c \
library/libuser1/thething/uiuxitem/widget/vkbd.keyboard.c \
library/libuser1/thething/virtimag/test/test.palette.c \
library/libuser1/thething/virtimag/test/test.codeimg.c \
library/libuser1/thething/virtimag/test/test.example.c \
library/libuser1/thething/virtimag/test/test.fractal.c \
library/libuser1/thething/virtimag/test/test.doodle.c \
library/libuser1/thething/virtimag/test/test.c \
library/libuser1/thething/virtimag/test/test.calib3d.c \
library/libuser1/thething/virtimag/term/tool.terminal.c \
library/libuser1/thething/virtimag/term/tool.terminal.helper.c \
library/libuser1/thething/virtimag/item.tardis.c \
library/libuser1/thething/virtimag/item.mario.c \
library/libuser1/thething/virtimag/tool/tool.calculator.c \
library/libuser1/thething/virtimag/tool/tool.browser.c \
library/libuser1/thething/virtimag/tool/menu.detail.c \
library/libuser1/thething/virtimag/tool/tool.sketchpad.c \
library/libuser1/thething/virtimag/tool/tool.editor.c \
library/libuser1/thething/virtimag/tool/uiux.voxel.c \
library/libuser1/thething/virtimag/tool/uiux.texmix.c \
library/libuser1/thething/virtimag/tool/tool.pwmtool.c \
library/libuser1/thething/virtimag/tool/uiux.spectrum.c \
library/libuser1/thething/virtimag/tool/tool.filesystem.c \
library/libuser1/thething/virtimag/tool/uiux.video.c \
library/libuser1/thething/virtimag/tool/menu.overview.c \
library/libuser1/thething/virtimag/tool/tool.wireshark.c \
library/libuser1/thething/virtimag/tool/uiux.oscillo.c \
library/libuser1/thething/virtimag/tool/tool.font.c \
library/libuser1/thething/virtimag/vmhw/ram/vmhw.sram.c \
library/libuser1/thething/virtimag/vmhw/ram/vmhw.dram.c \
library/libuser1/thething/virtimag/vmhw/cpu/vmhw.cpu.x8664.c \
library/libuser1/thething/virtimag/vmhw/cpu/vmhw.cpu.arm64.c \
library/libuser1/thething/virtimag/vmhw/rpi/vmhw.rpi.uart.c \
library/libuser1/thething/virtimag/vmhw/rpi/vmhw.rpi.gpio.c \
library/libuser1/thething/virtimag/vmhw/vmhw.gpu.c \
library/libuser1/thething/thing.c \
library/libuser1/entity.c




#2
LOCAL_C_INCLUDES := $(LOCAL_PATH)/library
LOCAL_CFLAGS := -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast
LOCAL_LDLIBS := -lm -llog -ljnigraphics -landroid -lEGL -lGLESv3
LOCAL_MODULE := finalanswer
LOCAL_STATIC_LIBRARIES := android_native_app_glue

include $(BUILD_SHARED_LIBRARY)
$(call import-module,android/native_app_glue)
