/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test */

#ifndef _Included_com_example_test
#define _Included_com_example_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_test_get
  (JNIEnv *, jclass);

/*
 * Class:     com_example_test
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_test_set
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
