/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test */

#ifndef _Included_com_example_test
#define _Included_com_example_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test
 * Method:    birth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_birth
  (JNIEnv *, jclass);

/*
 * Class:     com_example_test
 * Method:    death
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_death
  (JNIEnv *, jclass);

/*
 * Class:     com_example_test
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
